USE [master]
GO

/****** Object:  Database [ATM]    Script Date: 13.3.2015 г. 10:45:36 ч. ******/
CREATE DATABASE [ATM]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ATM', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\ATM.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'ATM_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\ATM_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [ATM] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ATM].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ATM] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ATM] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ATM] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ATM] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ATM] SET ARITHABORT OFF 
GO

ALTER DATABASE [ATM] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ATM] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ATM] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ATM] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ATM] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ATM] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ATM] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ATM] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ATM] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ATM] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ATM] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ATM] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ATM] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ATM] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ATM] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ATM] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ATM] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ATM] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [ATM] SET  MULTI_USER 
GO

ALTER DATABASE [ATM] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ATM] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ATM] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ATM] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [ATM] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ATM] SET  READ_WRITE 
GO

USE [ATM]
GO

/****** Object:  Table [dbo].[CardAccounts]    Script Date: 13.3.2015 г. 10:50:34 ч. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CardAccounts](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[CardNumber] [nchar](10) NOT NULL,
	[CardPIN] [nchar](4) NOT NULL,
	[CardCach] [money] NOT NULL,
 CONSTRAINT [PK_CardAccounts] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UK_CardAccounts] UNIQUE NONCLUSTERED 
(
	[CardNumber] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

INSERT INTO [dbo].[CardAccounts] ([CardNumber], [CardPIN], [CarsCach]) VALUES ('1001001111', '1111', 750)
INSERT INTO [dbo].[CardAccounts] ([CardNumber], [CardPIN], [CarsCach]) VALUES ('1002002222', '2222', 200)
INSERT INTO [dbo].[CardAccounts] ([CardNumber], [CardPIN], [CarsCach]) VALUES ('1003003333', '3333', 365)
INSERT INTO [dbo].[CardAccounts] ([CardNumber], [CardPIN], [CarsCach]) VALUES ('2001002323', '2323', 505)
INSERT INTO [dbo].[CardAccounts] ([CardNumber], [CardPIN], [CarsCach]) VALUES ('2002005566', '5566', 1230)
GO

/****** Object:  Table [dbo].[TransactionHistory]    Script Date: 14.3.2015 г. 18:36:25 ч. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TransactionHistory](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[CardNumber] [nchar](10) NOT NULL,
	[TransactionDate] [datetime] NOT NULL,
	[Amount] [money] NOT NULL,
 CONSTRAINT [PK_TransactionHistory] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[TransactionHistory]  WITH CHECK ADD  CONSTRAINT [FK_TransactionHistory_CardAccounts] FOREIGN KEY([CardNumber])
REFERENCES [dbo].[CardAccounts] ([CardNumber])
GO

ALTER TABLE [dbo].[TransactionHistory] CHECK CONSTRAINT [FK_TransactionHistory_CardAccounts]
GO